version: '2'

services:
  web-platform:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_SLAITE_API = "$NEXT_PUBLIC_SLAITE_API"
    
